apiVersion: v1
description: A Helm chart for From Monolith to K8s Conference App
name: fmtok8s-app
version: 0.0.85
type: application
icon: https://rawgit.com/jenkins-x/jenkins-x-platform/08df980/images/kubernetes.png
appVersion: 1.0.0
maintainers: 
  - name: salaboy
    email: salaboy at gmail dot com
    url: http://salaboy.com
home: http://github.com/salaboy/from-monolith-to-k8s    
keywords:
  - cloudnative
  - example
  - cd
  - kubernetes
  - tutorial
