apiVersion: v1
appVersion: 0.0.14
description: A Helm chart for From Monolith to K8s Conference App
icon: https://rawgit.com/jenkins-x/jenkins-x-platform/08df980/images/kubernetes.png
name: fmtok8s-app
version: 0.0.14
