apiVersion: v1
description: A Helm chart for From Monolith to K8s Conference App
name: fmtok8s-app
version: 0.0.83
icon: https://rawgit.com/jenkins-x/jenkins-x-platform/08df980/images/kubernetes.png
appVersion: 1.0.0
