apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone-pr.yaml
  name: pullrequest
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-boot:3.1.74
          name: jx-variables
          resources: {}
<<<<<<< HEAD
        - args:
          - cd /workspace/source/charts/fmtok8s-app && jx step helm build
          command:
          - /bin/sh
          - -c
          image: gcr.io/jenkinsxio/builder-maven:2.1.150-769
=======
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image:  gcr.io/jenkinsxio/jx-boot:3.1.74
>>>>>>> update jenkins-x (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (3ca699962b74084ba3766e343094f013238fb4ed) to master (fb3a12720f13d7f444e409eaea02f43a03b5e456)
          name: build-helm-build
          resources: {}
          script: |
            #!/bin/sh
            jx gitops helm build

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
