apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  annotations:
    lighthouse.jenkins-x.io/prependStepsURL: https://raw.githubusercontent.com/jenkins-x/jx3-pipeline-catalog/60bed6408732c1eda91a15713f51a9f97dcb1757/tasks/git-clone/git-clone.yaml
  name: release
spec:
  pipelineSpec:
    tasks:
    - name: from-build-pack
      resources: {}
      taskSpec:
        metadata: {}
        stepTemplate:
          name: ""
          resources:
            requests:
              cpu: 400m
              memory: 512Mi
          workingDir: /workspace/source
        steps:
        - image: gcr.io/jenkinsxio/jx-release-version:1.0.42
          name: next-version
          resources: {}
<<<<<<< HEAD
          workingDir: /workspace
        - args:
          - gitops
          - git
          - setup
          - --namespace
          - jx-git-operator
          command:
          - jx
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: git-setup
          resources: {}
          workingDir: /workspace
        - args:
          - -c
          - jx step next-version --use-git-tag-only --tag
          command:
          - /bin/sh
          image: gcr.io/jenkinsxio-labs-private/jxl:0.0.136
          name: tag-with-new-version
          resources: {}
        - args:
          - '[ -d /builder/home ] || mkdir -p /builder && ln -s /tekton/home /builder/home'
          command:
          - /bin/sh
          - -c
          image: gcr.io/jenkinsxio/builder-jx:2.1.142-761
          name: setup-builder-home
          resources: {}
        - args:
          - gitops
          - variables
          command:
          - jx
          image: gcr.io/jenkinsxio/jx-cli:latest
          name: jx-variables
          resources: {}
        - args:
          - cd /workspace/source/charts/fmtok8s-app && jx step helm build --verbose
          command:
          - /bin/sh
          - -c
          image: gcr.io/jenkinsxio/builder-maven:2.1.150-769
          name: build-helm-build
          resources: {}
        - args:
          - source /workspace/source/.jx/variables.sh && jx step changelog --version v${VERSION}
          command:
          - /bin/bash
          - -c
          image: gcr.io/jenkinsxio/builder-go:2.1.142-761
=======
          script: |
            #!/usr/bin/env bash
            VERSION=$(jx-release-version)
            echo $VERSION > VERSION

        - image: gcr.io/jenkinsxio/jx-boot:3.1.74
          name: jx-variables
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops variables
        - image: gcr.io/jenkinsxio/jx-changelog:0.0.17
>>>>>>> update jenkins-x (https://github.com/jenkins-x/jx3-pipeline-catalog) from master (3ca699962b74084ba3766e343094f013238fb4ed) to master (fb3a12720f13d7f444e409eaea02f43a03b5e456)
          name: promote-changelog
          resources: {}
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh

            if [ -d "/workspace/source/charts/$REPO_NAME" ]; then
            sed -i -e "s/^version:.*/version: $VERSION/" ./charts/$REPO_NAME/Chart.yaml
            sed -i -e "s/repository:.*/repository: $DOCKER_REGISTRY\/$DOCKER_REGISTRY_ORG\/$APP_NAME/" ./charts/$REPO_NAME/values.yaml
            sed -i -e "s/tag:.*/tag: $VERSION/" ./charts/$REPO_NAME/values.yaml;
            else echo no charts; fi

            git commit -a -m "chore: release $VERSION" --allow-empty
            git tag -fa v$VERSION -m "Release version $VERSION"
            git push origin v$VERSION

            jx changelog create --version v${VERSION}
        - image: gcr.io/jenkinsxio/jx-boot:3.1.74
          name: promote-helm-release
          resources: {}
          script: |
            #!/usr/bin/env sh
            jx gitops helm release
        - image: gcr.io/jenkinsxio/jx-promote:0.0.159
          name: promote-jx-promote
          resources: {}
          script: |
            #!/usr/bin/env sh
            source /workspace/source/.jx/variables.sh
            jx promote -b --all-auto --timeout 1h --no-poll

  podTemplate: {}
  serviceAccountName: tekton-bot
  timeout: 240h0m0s
status: {}
